POST https://vendors.lightup.com.ng/AccessToken HTTP/1.1
content-type: application/x-www-form-urlencoded

{
    "username": "general@demo.com",
    "password": "G3n3ral@dem0.com",
    "grant_type": "password"
}

###

GET http://croberts-001-site2.ftempurl.com/randglobal/apis/interswitch/billers HTTP/1.1